spring:
  profiles:
    active: local
#    active: develop // 개발 서버
#    active: real // 운영 서버

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # 운영 단계에서는 ddl-auto 를 지우고 아예 사용도 하지 말 것
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    # true(default): 요청 부터 응답 하기 직전까지 영속성 컨텍스트, DB 커넥션 유지
    # false: 트렌젝션(@Transaction)이 설정된 시점까지 영속성 컨텍스트, DB 커넥션
    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug
