spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    # 해당 옵션을 false 설정할 경우 트렌잭션 단위로 조회가 가능하고
    # 현재 프로젝트에서 service 단위에 설정하여 컨트롤러에선 영속성 조회가 안될 수 있음
    open-in-view: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org.hibernate.SQL: debug

